<?php

declare(strict_types=1);

namespace WaffleTests\Commons\Console\Compiler;

use PHPUnit\Framework\Attributes\CoversClass;
use ReflectionObject;
use RuntimeException;
use Waffle\Commons\Console\Compiler\ContainerCompiler;
use Waffle\Commons\Console\Exception\CompilerException;
use Waffle\Commons\Contracts\Container\CompiledContainerInterface;
use Waffle\Commons\Contracts\Container\ContainerInterface;
use WaffleTests\Commons\Console\AbstractTestCase;
use WaffleTests\Commons\Console\Compiler\Fixture\AbstractServiceBase;
use WaffleTests\Commons\Console\Compiler\Fixture\BuiltinUnionDefaultService;
use WaffleTests\Commons\Console\Compiler\Fixture\FakeRuntimeContainer;
use WaffleTests\Commons\Console\Compiler\Fixture\Greeter;
use WaffleTests\Commons\Console\Compiler\Fixture\GreeterInterface;
use WaffleTests\Commons\Console\Compiler\Fixture\IntersectionDependentService;
use WaffleTests\Commons\Console\Compiler\Fixture\IntKeyedDefinitionsContainer;
use WaffleTests\Commons\Console\Compiler\Fixture\LeafService;
use WaffleTests\Commons\Console\Compiler\Fixture\MidService;
use WaffleTests\Commons\Console\Compiler\Fixture\NonArrayDefinitionsContainer;
use WaffleTests\Commons\Console\Compiler\Fixture\NullableUnionDependentService;
use WaffleTests\Commons\Console\Compiler\Fixture\OptionalDependentService;
use WaffleTests\Commons\Console\Compiler\Fixture\ResettableLeafService;
use WaffleTests\Commons\Console\Compiler\Fixture\RootService;
use WaffleTests\Commons\Console\Compiler\Fixture\ScalarDefaultsService;
use WaffleTests\Commons\Console\Compiler\Fixture\SecondUnionService;
use WaffleTests\Commons\Console\Compiler\Fixture\UnionDefaultService;
use WaffleTests\Commons\Console\Compiler\Fixture\UnionDependentService;
use WaffleTests\Commons\Console\Compiler\Fixture\VariadicService;

/**
 * AOT-01 graph-identity gate.
 *
 * Boots a small synthetic service graph in a runtime container, builds every
 * service and captures a normalised signature (id → concrete FQCN → recursive
 * constructor-arg FQCNs). Then it compiles the container, loads the generated
 * `CompiledContainer`, captures the SAME signature, and asserts the two graphs
 * are deep-equal (FQCN-normalised, NOT object identity).
 *
 * Closure-passthrough set documented by {@see self::testClosureAndObjectPassthrough()}:
 * closures (lazy factories) and pre-registered objects are NOT inlined; the
 * compiled `get()` delegates them to the composed runtime container verbatim.
 */
#[CoversClass(ContainerCompiler::class)]
final class ContainerCompilerTest extends AbstractTestCase
{
    /** @var list<string> Files generated by the test, cleaned up in tearDown(). */
    private array $artifacts = [];

    #[\Override]
    protected function tearDown(): void
    {
        foreach ($this->artifacts as $file) {
            if (!is_file($file)) {
                continue;
            }

            @unlink($file);
        }
        $this->artifacts = [];
        parent::tearDown();
    }

    /**
     * Registers the synthetic graph onto a fresh runtime container double.
     */
    private function seed(FakeRuntimeContainer $container): void
    {
        $container->set(LeafService::class, LeafService::class);
        $container->set(MidService::class, MidService::class);
        $container->set(RootService::class, RootService::class);
        $container->set(ResettableLeafService::class, ResettableLeafService::class);
        // Interface keyed to a concrete (interface-bound autowiring).
        $container->set(GreeterInterface::class, Greeter::class);

        // AOT-01: a service with an UNREGISTERED, nullable-with-default class
        // dependency (the interface is never bound). Autowire resolves it to null;
        // a compiler that eagerly emitted get() would throw, diverging the graph.
        $container->set(OptionalDependentService::class, OptionalDependentService::class);

        // AOT-05: a service with a UNION dependency whose first member is unbound
        // and whose second member is registered — Autowire selects the second.
        $container->set(SecondUnionService::class, SecondUnionService::class);
        $container->set(UnionDependentService::class, UnionDependentService::class);

        // AOT-05 edge: a union mixing a class member with a builtin and a default.
        // No member is registered → Autowire (and the compiled wiring) fall back to
        // the declared default.
        $container->set(UnionDefaultService::class, UnionDefaultService::class);
    }

    /**
     * @return list<string> The service ids the snapshot compares.
     */
    private function snapshotIds(): array
    {
        return [
            LeafService::class,
            MidService::class,
            RootService::class,
            ResettableLeafService::class,
            GreeterInterface::class,
            OptionalDependentService::class,
            UnionDependentService::class,
            UnionDefaultService::class,
        ];
    }

    public function testCompiledGraphIsIdenticalToRuntimeGraph(): void
    {
        // 1. Runtime container — build each service, capture the signature.
        $runtime = new FakeRuntimeContainer();
        $this->seed($runtime);
        $runtimeSignature = $this->signatureOf($runtime, $this->snapshotIds());

        // 2. Compile to source against a FRESH (just-seeded) runtime container so
        //    the compiler reads its `definitions` map.
        $compilerInput = new FakeRuntimeContainer();
        $this->seed($compilerInput);
        $compiled = $this->loadCompiledContainer($compilerInput, 'GraphIdentity');

        // 3. Compiled container — same signature.
        $compiledSignature = $this->signatureOf($compiled, $this->snapshotIds());

        // 4. Deep-equal (FQCN-normalised graphs).
        static::assertSame($runtimeSignature, $compiledSignature);

        // Sanity: the deepest path resolved to the right concrete classes.
        static::assertSame(RootService::class, $compiledSignature[RootService::class]['fqcn']);
        static::assertSame(
            Greeter::class,
            $compiledSignature[GreeterInterface::class]['fqcn'],
            'interface id must resolve to its bound concrete in the compiled graph',
        );
    }

    public function testUnregisteredNullableDependencyResolvesToNull(): void
    {
        // AOT-01: the dependency interface is never bound, so the runtime
        // container's has() reports it absent. Autowire returns null for the
        // nullable-with-default parameter; the compiled container must do the same
        // (the pre-fix compiler emitted a bare get() that would have thrown).
        $runtime = new FakeRuntimeContainer();
        $this->seed($runtime);
        $runtimeService = $runtime->get(OptionalDependentService::class);
        static::assertInstanceOf(OptionalDependentService::class, $runtimeService);
        static::assertNull($runtimeService->optional, 'baseline: Autowire resolves the unbound nullable dep to null');

        $input = new FakeRuntimeContainer();
        $this->seed($input);
        $compiled = $this->loadCompiledContainer($input, 'OptionalNullable');

        $compiledService = $compiled->get(OptionalDependentService::class);
        static::assertInstanceOf(OptionalDependentService::class, $compiledService);
        static::assertNull(
            $compiledService->optional,
            'compiled container must mirror Autowire and inject null for the unregistered nullable dep',
        );
    }

    public function testUnionDependencyResolvesToFirstRegisteredMember(): void
    {
        // AOT-05: the union is FirstUnionInterface|SecondUnionService. The first
        // member is unbound; Autowire (and so the compiled container) must select
        // the registered SECOND member, not unconditionally resolve the first.
        $runtime = new FakeRuntimeContainer();
        $this->seed($runtime);
        $runtimeService = $runtime->get(UnionDependentService::class);
        static::assertInstanceOf(UnionDependentService::class, $runtimeService);
        static::assertInstanceOf(
            SecondUnionService::class,
            $runtimeService->dependency,
            'baseline: Autowire selects the first registered union member (the second declared one)',
        );

        $input = new FakeRuntimeContainer();
        $this->seed($input);
        $compiled = $this->loadCompiledContainer($input, 'UnionSecond');

        $compiledService = $compiled->get(UnionDependentService::class);
        static::assertInstanceOf(UnionDependentService::class, $compiledService);
        static::assertInstanceOf(
            SecondUnionService::class,
            $compiledService->dependency,
            'compiled container must select the first REGISTERED union member, matching Autowire',
        );
    }

    public function testUnionWithBuiltinMemberAndNoRegisteredMemberFallsBackToDefault(): void
    {
        // AOT-05 edge: the union is FirstUnionInterface|int with a default of 7.
        // No member is registered, so both Autowire and the compiled container use
        // the declared default — exercising the builtin-skip and default-fallback
        // branches of the union emission.
        $runtime = new FakeRuntimeContainer();
        $this->seed($runtime);
        $runtimeService = $runtime->get(UnionDefaultService::class);
        static::assertInstanceOf(UnionDefaultService::class, $runtimeService);
        static::assertSame(7, $runtimeService->value, 'baseline: Autowire falls back to the union default');

        $input = new FakeRuntimeContainer();
        $this->seed($input);
        $compiled = $this->loadCompiledContainer($input, 'UnionDefault');

        $compiledService = $compiled->get(UnionDefaultService::class);
        static::assertInstanceOf(UnionDefaultService::class, $compiledService);
        static::assertSame(
            7,
            $compiledService->value,
            'compiled container must fall back to the union default like Autowire',
        );
    }

    public function testCompiledContainerReturnsSingletons(): void
    {
        $input = new FakeRuntimeContainer();
        $this->seed($input);
        $compiled = $this->loadCompiledContainer($input, 'Singletons');

        $a = $compiled->get(RootService::class);
        $b = $compiled->get(RootService::class);
        static::assertSame($a, $b, 'compiled get() must memoise singletons');
    }

    public function testCompiledContainerImplementsTheMarker(): void
    {
        $input = new FakeRuntimeContainer();
        $this->seed($input);
        $compiled = $this->loadCompiledContainer($input, 'Marker');

        static::assertInstanceOf(CompiledContainerInterface::class, $compiled);
    }

    public function testResetCascadesToInlinedResettableServices(): void
    {
        $input = new FakeRuntimeContainer();
        $this->seed($input);
        $compiled = $this->loadCompiledContainer($input, 'Reset');

        $service = $compiled->get(ResettableLeafService::class);
        static::assertInstanceOf(ResettableLeafService::class, $service);
        $service->touch();
        $service->touch();
        static::assertSame(2, $service->touches);

        $compiled->reset();
        static::assertSame(0, $service->touches, 'reset() must cascade to inlined resettable singletons');
    }

    public function testHasDelegatesToRuntimeContainer(): void
    {
        $input = new FakeRuntimeContainer();
        $this->seed($input);
        $compiled = $this->loadCompiledContainer($input, 'Has');

        static::assertTrue($compiled->has(LeafService::class));
        static::assertFalse($compiled->has('Nope\\Unregistered'));
    }

    public function testClosureAndObjectPassthrough(): void
    {
        $input = new FakeRuntimeContainer();
        $this->seed($input);

        // A closure factory (lazy) and a pre-built object — both non-inlinable.
        $input->set('factory.service', static fn(): LeafService => new LeafService());
        $prebuilt = new LeafService();
        $input->set('prebuilt.service', $prebuilt);

        $compiled = $this->loadCompiledContainer($input, 'Passthrough');

        // The closure is invoked through the composed runtime container.
        static::assertInstanceOf(LeafService::class, $compiled->get('factory.service'));
        // The pre-registered object passes through by identity.
        static::assertSame($prebuilt, $compiled->get('prebuilt.service'));
    }

    public function testCompilingAContainerWithoutDefinitionsMapThrows(): void
    {
        $opaque = new class implements ContainerInterface {
            #[\Override]
            public function get(string $id): mixed
            {
                return null;
            }

            #[\Override]
            public function has(string $id): bool
            {
                return false;
            }

            #[\Override]
            public function set(string $id, object|callable|string $concrete): void {}

            #[\Override]
            public function reset(): void {}
        };

        $this->expectException(CompilerException::class);
        new ContainerCompiler()->compile($opaque);
    }

    public function testEmptyMatchArmStillCompiles(): void
    {
        // A container whose only definitions are non-inlinable (a closure) produces
        // a compiled get() whose match has only the default arm.
        $input = new FakeRuntimeContainer();
        $input->set('only.factory', static fn(): LeafService => new LeafService());

        $compiled = $this->loadCompiledContainer($input, 'EmptyMatch');

        static::assertInstanceOf(LeafService::class, $compiled->get('only.factory'));
    }

    public function testAbstractClassDefinitionIsNotInlinedAndPassesThrough(): void
    {
        // An ABSTRACT class registered as a concrete is not instantiable, so the
        // compiler must NOT emit a `new` arm for it — it falls through to the
        // composed runtime container's default arm (AOT-01 passthrough).
        $input = new FakeRuntimeContainer();
        $input->set(LeafService::class, LeafService::class);
        $input->set(AbstractServiceBase::class, AbstractServiceBase::class);

        $source = new ContainerCompiler()->compile(
            $input,
            'WaffleTests\\Commons\\Console\\Compiler\\Generated',
            'CompiledAbstract',
            FakeRuntimeContainer::class,
        );

        // Inlinable concrete IS emitted as a match arm…
        static::assertStringContainsString(
            sprintf("'%s' => new \\%s()", $this->sourceQuotedKey(LeafService::class), LeafService::class),
            $source,
            'an instantiable class with no ctor must be inlined',
        );
        // …the abstract class is NOT emitted as an arm (no `new \…AbstractServiceBase`).
        static::assertStringNotContainsString(
            '\\' . AbstractServiceBase::class . '(',
            $source,
            'a non-instantiable/abstract class must not be inlined; it passes through',
        );
    }

    public function testIntersectionTypedConstructorParameterPreventsInlining(): void
    {
        // An intersection-typed ctor parameter is not statically resolvable, so the
        // whole definition becomes a passthrough rather than an inlined `new`.
        $input = new FakeRuntimeContainer();
        $input->set(IntersectionDependentService::class, IntersectionDependentService::class);

        $source = new ContainerCompiler()->compile(
            $input,
            'WaffleTests\\Commons\\Console\\Compiler\\Generated',
            'CompiledIntersection',
            FakeRuntimeContainer::class,
        );

        static::assertStringNotContainsString(
            '\\' . IntersectionDependentService::class . '(',
            $source,
            'a class with an intersection-typed ctor param must not be inlined',
        );
        // Only the default (runtime passthrough) arm survives for this graph.
        static::assertStringContainsString('default => $this->runtime->get($id)', $source);
    }

    public function testInlinableVariadicConstructorEmitsLeadingArgsAndStopsAtVariadic(): void
    {
        // A variadic ctor is inlinable: the compiler emits the leading positional
        // dependency and stops at the variadic (the container cannot collect a
        // variadic service list). The generated wiring builds with an empty variadic.
        $input = new FakeRuntimeContainer();
        $input->set(LeafService::class, LeafService::class);
        $input->set(VariadicService::class, VariadicService::class);

        $compiled = $this->loadCompiledContainer($input, 'Variadic');

        $service = $compiled->get(VariadicService::class);
        static::assertInstanceOf(VariadicService::class, $service);
        static::assertInstanceOf(LeafService::class, $service->leaf);
        static::assertSame([], $service->tags, 'the variadic tail is left empty by the compiled wiring');
    }

    public function testBuiltinOnlyUnionFallsBackToParameterDefault(): void
    {
        // A union of ONLY builtin members (int|string) with a default has no class
        // candidate, so the compiler resolves it to the declared default — both at
        // emission and at runtime.
        $runtime = new FakeRuntimeContainer();
        $runtime->set(BuiltinUnionDefaultService::class, BuiltinUnionDefaultService::class);
        $runtimeService = $runtime->get(BuiltinUnionDefaultService::class);
        static::assertInstanceOf(BuiltinUnionDefaultService::class, $runtimeService);
        static::assertSame(42, $runtimeService->value, 'baseline: Autowire uses the builtin-union default');

        $input = new FakeRuntimeContainer();
        $input->set(BuiltinUnionDefaultService::class, BuiltinUnionDefaultService::class);
        $compiled = $this->loadCompiledContainer($input, 'BuiltinUnion');

        $service = $compiled->get(BuiltinUnionDefaultService::class);
        static::assertInstanceOf(BuiltinUnionDefaultService::class, $service);
        static::assertSame(42, $service->value, 'compiled wiring must fall back to the builtin-union default');
    }

    public function testNullableUnionWithNoRegisteredMemberThrowsLikeAutowire(): void
    {
        // A nullable union (A|B|null) with no default and no registered member.
        // Autowire's union resolver does NOT honour nullability — with no candidate
        // and no default it THROWS. The compiled wiring must mirror that throw
        // instead of short-circuiting to null (graph-identity: a null short-circuit
        // would diverge from the runtime container, which raises here).
        $runtime = new FakeRuntimeContainer();
        $runtime->set(NullableUnionDependentService::class, NullableUnionDependentService::class);

        $runtimeThrew = false;
        try {
            $runtime->get(NullableUnionDependentService::class);
        } catch (RuntimeException) {
            $runtimeThrew = true;
        }
        static::assertTrue(
            $runtimeThrew,
            'baseline: Autowire throws for an unregistered nullable union with no default',
        );

        $input = new FakeRuntimeContainer();
        $input->set(NullableUnionDependentService::class, NullableUnionDependentService::class);
        $compiled = $this->loadCompiledContainer($input, 'NullableUnion');

        // The emitted source resolves the first union candidate (which throws for an
        // unregistered id) — NOT a `null` short-circuit.
        $this->expectException(RuntimeException::class);
        $compiled->get(NullableUnionDependentService::class);
    }

    public function testExportsEveryScalarDefaultKind(): void
    {
        // Drives every arm of exportValue(): bool, int, float, string and array
        // defaults must round-trip to the exact values Autowire would have used.
        $runtime = new FakeRuntimeContainer();
        $runtime->set(LeafService::class, LeafService::class);
        $runtime->set(ScalarDefaultsService::class, ScalarDefaultsService::class);
        $runtimeService = $runtime->get(ScalarDefaultsService::class);
        static::assertInstanceOf(ScalarDefaultsService::class, $runtimeService);

        $input = new FakeRuntimeContainer();
        $input->set(LeafService::class, LeafService::class);
        $input->set(ScalarDefaultsService::class, ScalarDefaultsService::class);
        $compiled = $this->loadCompiledContainer($input, 'ScalarDefaults');

        $service = $compiled->get(ScalarDefaultsService::class);
        static::assertInstanceOf(ScalarDefaultsService::class, $service);
        static::assertNull($service->maybe, 'null default must round-trip');
        static::assertTrue($service->flag, 'bool default must round-trip');
        static::assertSame(3, $service->count, 'int default must round-trip');
        static::assertSame(1.5, $service->ratio, 'float default must round-trip');
        static::assertSame('scalars', $service->label, 'string default must round-trip');
        static::assertSame(['a' => 1, 'b' => 2], $service->options, 'array default must round-trip');
    }

    public function testSkipsNonStringDefinitionIds(): void
    {
        // A definitions map mixing an int key with a string key: the compiler skips
        // the non-string id and still inlines the string-keyed concrete.
        $source = new ContainerCompiler()->compile(
            new IntKeyedDefinitionsContainer(),
            'WaffleTests\\Commons\\Console\\Compiler\\Generated',
            'CompiledIntKeyed',
            FakeRuntimeContainer::class,
        );

        static::assertStringContainsString(
            sprintf("'%s' => new \\%s()", $this->sourceQuotedKey(LeafService::class), LeafService::class),
            $source,
            'the string-keyed concrete must still be inlined',
        );
        // The numeric id is never emitted as a quoted match key.
        static::assertStringNotContainsString('            0 => ', $source);
    }

    public function testThrowsWhenDefinitionsPropertyIsNotAnArray(): void
    {
        $this->expectException(CompilerException::class);
        $this->expectExceptionMessage('not an array');

        new ContainerCompiler()->compile(new NonArrayDefinitionsContainer());
    }

    /**
     * Mirrors `ContainerCompiler::quote()`'s backslash doubling so a match-arm key
     * can be matched verbatim in the generated source.
     */
    private function sourceQuotedKey(string $fqcn): string
    {
        return str_replace('\\', '\\\\', $fqcn);
    }

    /**
     * Captures id → {fqcn, args:[recursive signatures]} for each id, walking the
     * BUILT objects' constructor arguments by reflection. FQCN-normalised: object
     * identity is irrelevant, only concrete classes + wiring shape.
     *
     * @param list<string> $ids
     * @return array<string, array{fqcn: string, args: array<string, mixed>}>
     */
    private function signatureOf(ContainerInterface $container, array $ids): array
    {
        $signature = [];
        foreach ($ids as $id) {
            $instance = $container->get($id);
            $signature[$id] = $this->describe($instance);
        }

        return $signature;
    }

    /**
     * @return array{fqcn: string, args: array<string, mixed>}
     */
    private function describe(mixed $instance): array
    {
        if (!is_object($instance)) {
            return ['fqcn' => get_debug_type($instance), 'args' => []];
        }

        $reflection = new ReflectionObject($instance);
        $args = [];
        foreach ($reflection->getProperties() as $property) {
            $value = $property->getValue($instance);
            $args[$property->getName()] = is_object($value)
                ? $this->describe($value)
                : ['fqcn' => get_debug_type($value), 'args' => []];
        }

        return ['fqcn' => $instance::class, 'args' => $args];
    }

    /**
     * Compiles $input to source, writes it to a temp artifact, requires it, and
     * returns a CompiledContainer composing a FRESH (re-seeded) runtime container.
     */
    private function loadCompiledContainer(FakeRuntimeContainer $input, string $tag): CompiledContainerInterface
    {
        $namespace = 'WaffleTests\\Commons\\Console\\Compiler\\Generated';
        $className = 'CompiledContainer' . $tag;

        $source = new ContainerCompiler()->compile($input, $namespace, $className, FakeRuntimeContainer::class);

        $file = sys_get_temp_dir() . '/' . $className . '_' . uniqid() . '.php';
        file_put_contents($file, $source);
        $this->artifacts[] = $file;

        require $file;

        // The generated container composes the SAME (already-seeded) runtime
        // container the compiler inspected — its closures/objects live there.
        $fqcn = $namespace . '\\' . $className;
        $instance = new $fqcn($input);
        static::assertInstanceOf(CompiledContainerInterface::class, $instance);

        return $instance;
    }
}
